server:
  port: 8000 
  servlet:
    encoding: 
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/** 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cndurpat9itp.ap-northeast-2.rds.amazonaws.com:3306/todolist?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: 1q2w3e4r
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
